"""Stamps the commit the firmware was built from into a header.

Generated into the build directory rather than into src, so building a tree
never dirties the tree it is describing - the same reason secrets.py writes
where it does.
"""

import os
import subprocess

Import("env")  # noqa: F821  - injected by PlatformIO

HERE = env.subst("$PROJECT_DIR")  # noqa: F821


def git(*args):
    try:
        out = subprocess.check_output(
            ["git"] + list(args), cwd=HERE, stderr=subprocess.DEVNULL
        )
    except (OSError, subprocess.CalledProcessError):
        return ""
    return out.decode("utf-8", "replace").strip()


# A checkout without git, or an archive of one, still builds - it just does not
# know where it came from.
commit = git("rev-parse", "--short=7", "HEAD") or "unknown"
# A plus for a tree with changes in it. Through a development session the tree is
# dirty on nearly every flash, so the bare hash names a commit whose code is not
# what is running - and the pre-commit build is stamped with the parent, which is
# the same lie one commit further back. The plus is the whole of what it can
# honestly say.
if git("status", "--porcelain"):
    commit += "+"

out_dir = os.path.join(env.subst("$BUILD_DIR"), "generated")  # noqa: F821
os.makedirs(out_dir, exist_ok=True)
path = os.path.join(out_dir, "version.h")
body = (
    "// Generated by version.py. Do not edit.\n"
    "#pragma once\n\n"
    '#define BUILD_COMMIT "{}"\n'.format(commit)
)

# Only when it has actually changed. Rewritten every build, the header's mtime
# moves every build and everything that includes it is rebuilt for nothing.
if not os.path.exists(path) or open(path, encoding="utf-8").read() != body:
    with open(path, "w", encoding="utf-8") as handle:
        handle.write(body)

env.Append(CPPPATH=[out_dir])  # noqa: F821
print("version.py: built from {}".format(commit))
